//
// File was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.07.18 at 11:42:48 AM CEST
//


package com.tieto.wro.java.a17.wunderground.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="termsofService" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="features">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="feature" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="results">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="result" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="country_iso3166" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="country_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="zmw" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="l" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"version",
		"termsofService",
		"features",
		"results"
})
@XmlRootElement(name = "response")
public class MultipleResponse implements IResponse {

	protected float version;
	@XmlElement(required = true)
	protected String termsofService;
	@XmlElement(required = true)
	protected MultipleResponse.Features features;
	@XmlElement(required = true)
	protected MultipleResponse.Results results;

	/**
	 * Gets the value of the version property.
	 *
	 */
	public float getVersion() {
		return version;
	}

	/**
	 * Sets the value of the version property.
	 *
	 */
	public void setVersion(float value) {
		this.version = value;
	}

	/**
	 * Gets the value of the termsofService property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getTermsofService() {
		return termsofService;
	}

	/**
	 * Sets the value of the termsofService property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setTermsofService(String value) {
		this.termsofService = value;
	}

	/**
	 * Gets the value of the features property.
	 *
	 * @return
	 *     possible object is
	 *     {@link MultipleResponse.Features }
	 *
	 */
	public MultipleResponse.Features getFeatures() {
		return features;
	}

	/**
	 * Sets the value of the features property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link MultipleResponse.Features }
	 *
	 */
	public void setFeatures(MultipleResponse.Features value) {
		this.features = value;
	}

	/**
	 * Gets the value of the results property.
	 *
	 * @return
	 *     possible object is
	 *     {@link MultipleResponse.Results }
	 *
	 */
	public MultipleResponse.Results getResults() {
		return results;
	}

	/**
	 * Sets the value of the results property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link MultipleResponse.Results }
	 *
	 */
	public void setResults(MultipleResponse.Results value) {
		this.results = value;
	}


	/**
	 * <p>Java class for anonymous complex type.
	 *
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="feature" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"feature"
	})
	public static class Features {

		@XmlElement(required = true)
		protected String feature;

		/**
		 * Gets the value of the feature property.
		 *
		 * @return
		 *     possible object is
		 *     {@link String }
		 *
		 */
		public String getFeature() {
			return feature;
		}

		/**
		 * Sets the value of the feature property.
		 *
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 *
		 */
		public void setFeature(String value) {
			this.feature = value;
		}

	}


	/**
	 * <p>Java class for anonymous complex type.
	 *
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="result" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="country_iso3166" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="country_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="zmw" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="l" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"result"
	})
	public static class Results {

		protected List<MultipleResponse.Results.Result> result;

		/**
		 * Gets the value of the result property.
		 *
		 * <p>
		 * This accessor method returns a reference to the live list,
		 * not a snapshot. Therefore any modification you make to the
		 * returned list will be present inside the JAXB object.
		 * This is why there is not a <CODE>set</CODE> method for the result property.
		 *
		 * <p>
		 * For example, to add a new item, do as follows:
		 * <pre>
		 *    getResult().add(newItem);
		 * </pre>
		 *
		 *
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link MultipleResponse.Results.Result }
		 *
		 *
		 */
		public List<MultipleResponse.Results.Result> getResult() {
			if (result == null) {
				result = new ArrayList<MultipleResponse.Results.Result>();
			}
			return this.result;
		}


		/**
		 * <p>Java class for anonymous complex type.
		 *
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="country_iso3166" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="country_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="zmw" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="l" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"name",
				"city",
				"state",
				"country",
				"countryIso3166",
				"countryName",
				"zmw",
				"l"
		})
		public static class Result {

			@XmlElement(required = true)
			protected String name;
			@XmlElement(required = true)
			protected String city;
			@XmlElement(required = true)
			protected String state;
			@XmlElement(required = true)
			protected String country;
			@XmlElement(name = "country_iso3166", required = true)
			protected String countryIso3166;
			@XmlElement(name = "country_name", required = true)
			protected String countryName;
			@XmlElement(required = true)
			protected String zmw;
			@XmlElement(required = true)
			protected String l;

			/**
			 * Gets the value of the name property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getName() {
				return name;
			}

			/**
			 * Sets the value of the name property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setName(String value) {
				this.name = value;
			}

			/**
			 * Gets the value of the city property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getCity() {
				return city;
			}

			/**
			 * Sets the value of the city property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setCity(String value) {
				this.city = value;
			}

			/**
			 * Gets the value of the state property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getState() {
				return state;
			}

			/**
			 * Sets the value of the state property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setState(String value) {
				this.state = value;
			}

			/**
			 * Gets the value of the country property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getCountry() {
				return country;
			}

			/**
			 * Sets the value of the country property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setCountry(String value) {
				this.country = value;
			}

			/**
			 * Gets the value of the countryIso3166 property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getCountryIso3166() {
				return countryIso3166;
			}

			/**
			 * Sets the value of the countryIso3166 property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setCountryIso3166(String value) {
				this.countryIso3166 = value;
			}

			/**
			 * Gets the value of the countryName property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getCountryName() {
				return countryName;
			}

			/**
			 * Sets the value of the countryName property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setCountryName(String value) {
				this.countryName = value;
			}

			/**
			 * Gets the value of the zmw property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getZmw() {
				return zmw;
			}

			/**
			 * Sets the value of the zmw property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setZmw(String value) {
				this.zmw = value;
			}

			/**
			 * Gets the value of the l property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getL() {
				return l;
			}

			/**
			 * Sets the value of the l property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setL(String value) {
				this.l = value;
			}

		}

	}

}
